name: Release docker image

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service to release
        required: true
        type: choice
        options:
          - op-node
          - op-batcher
          - op-proposer
      version:
        description: Service version to publish (will be the docker tag)
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v4
        env:
          REGISTRY: ghcr.io
          REPOSITORY: fraxfinance/fraxtal
          PLATFORMS: linux/amd64,linux/arm64
          GIT_COMMIT: ${{ github.sha }}
          GIT_VERSION: ${{ inputs.version }}
          IMAGE_TAGS: ${{ inputs.version }}
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          targets: ${{ inputs.service }}
